### ISSUE TITLE
Crash Reported on Google Play Console

### ISSUE THREAD

**Issue by mrunal-upadhyay** [plaid/plaid-link-android#122]
# The problem

We observed 2 crashes reported in last 30 days on Google Play Store. We have not been able to reproduce the issue so far.

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | Android 10 (SDK 29) , Android 9 (SDK 28)             |
| Android Devices/Emulators    |Samsung Galaxy S10,  Samsung Galaxy S8+              |

# Logs

Type
java.lang.RuntimeException

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3116)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3259)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1950)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)
Caused by: kotlin.UninitializedPropertyAccessException: 
  at com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (BasePlaid.java:1)
  at com.plaid.internal.a.a (a.java:117)
  at com.plaid.internal.link.LinkWebViewActivity.onCreate (LinkWebViewActivity.java:2)
  at android.app.Activity.performCreate (Activity.java:7327)
  at android.app.Activity.performCreate (Activity.java:7318)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3096)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3259)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1950)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

**Comment by JeroenMols** [comment]
Hi @mrunal-upadhyay ,

First of all thanks for filing this bug report!
What version of the Android SDK are you seeing this on?

This feels quite similar to https://github.com/plaid/plaid-link-android/issues/105, where we fixed two root causes respectively in `3.1.1` and `3.2.1`.

**Comment by mrunal-upadhyay** [comment]
Thanks @JeroenMols for the update.

This is happening on 3.1.0 version of the sdk. We would update to latest version 3.2.2 and update you if we see this issue.

**Comment by JeroenMols** [comment]
Hi @mrunal-upadhyay 

Happy new year!

I was wondering whether you were already able to gather some data on whether this issue still occurs for you?

Thank you,
Jeroen

**Comment by joshuajamison** [comment]
Hi @JeroenMols 

I didn't report this specific issue, but I am still seeing a one instance of `UninitializedPropertyAccessException` on version `3.2.2`, definitely a huge improvement 👍 

Here's where I see it:

> Caused by kotlin.UninitializedPropertyAccessException
lateinit property INSTANCE has not been initialized
com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (SourceFile:1)
com.plaid.link.LinkActivity.getFactory (SourceFile:2)

`LinkWebViewActivity` issues specifically tho appear resolved for us for now though thankfully. I can file this separate if you'd prefer.

**Comment by ballerboiiii** [comment]
Yes would u please

**Comment by JeroenMols** [comment]
We've been trying to reproduce this with various permutations of enabling "Don't keep activities" and "zero background processes" and backgrouding + foregrounding our SDK in various stages of the Link flow.

Could you provide us a scenario where this exception still occurs?

Thanks!

**Comment by JeroenMols** [comment]
Closing this as we haven't heard back in 28days.

Please feel free to open a new ticket should the issue still persist.
