### ISSUE TITLE
plaid 依赖进去有问题

### ISSUE THREAD

**Issue by target1314** [plaid/plaid-link-android#139]
![image](https://user-images.githubusercontent.com/16127526/111620193-59fd4180-8821-11eb-8a9b-a18277d6ef4c.png)

无法解析pro.streem.pbandk公司：pbandk运行时-安卓：0.10.0-beta.2。

**Comment by JeroenMols** [comment]
Thanks for reporting this @target1314!

The dependency in question `pbandk-runtime-android:0.10.0-beta.2` only has a release variant published to jCenter() and Gradle's variant-aware dependency resolution isn't able to resolve a variant that matches the debug build type. (Note: this is already solved in the next `pbandk` release).

Can you try adding the following to your build.gradle file?

```kotlin
android {
    ...
    
    buildTypes {
        debug {
            matchingFallbacks += "release"
        }
    }
}
```

I'll get back to you when I have an ETA of a fix in our SDK.

**Comment by JeroenMols** [comment]
We've put out a new SDK release `3.2.6` with a fix.
Can you try upgrading to that one and let us know if that resolves your issue?

**Comment by sudansh** [comment]
Updating to 3.2.6 also doesn't fix the issue
getting the error
`Could not find pro.streem.pbandk:pbandk-runtime:0.10.0-beta.3.
Required by:
    project :base > com.plaid.link:sdk-core:3.2.6`

**Comment by JeroenMols** [comment]
@sudansh That looks like a different error, it seems like `pbandk` cannot be found altogether.

Have you added `jcenter()` as a maven repository under repositories?
source: https://plaid.com/docs/link/android/#update-your-project-plugins

```groovy
repositories {
        google()
        mavenCentral()
        jcenter()
}
```

While the Plaid Link SDK has already migrated to Maven Central, one of our dependencies has not, but we are working with them to migrate. https://github.com/streem/pbandk/issues/120

**Comment by sudansh** [comment]
@JeroenMols oh I was getting that error after I remove jcenter(). I will wait for the streem/pbandk to move to maven. Thanks

**Comment by JeroenMols** [comment]
@target1314 since we haven't heard from you in a while, we're going to assume this issue is fixed.
Thank you for filing and please feel free to reopen/file a new issue should you still run into new challenges.
