### ISSUE TITLE
Crash : Lateinit property component has not been initialized : getComponent$link_sdk_web_release(Plaid.java:1) [2.0.0]

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#84]
Plaid SDK version: 2.0.0
Issue: Crash recorded at Firebase
OS: Android 10
Device: Pixel 4
Crash Log:

      ```
       Fatal Exception: java.lang.RuntimeException: lateinit property component has not been initialized
       at com.plaid.link.Plaid.getComponent$link_sdk_web_release(Plaid.java:1)
       at com.plaid.link.internal.LinkActivity.onCreate(LinkActivity.java:2)
       at android.app.Activity.performCreate(Activity.java:7825)
       at android.app.Activity.performCreate(Activity.java:7814)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
```

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo This issue seems to be caused by not calling `Plaid.initialize()` before calling `openPlaidLink`.  Could you please check if that is the case?

**Comment by hitesh-banknovo** [comment]
Hi, Yes, I am calling this method `com.plaid.link.Plaid.initialize(application)` before opening the link.

**Comment by zsweigart** [comment]
Thanks for checking, can you provide your configuration (please exclude your public key) and the steps to reproduce it?

**Comment by hitesh-banknovo** [comment]
Here is my configuration to connect Plaid account

```
com.plaid.link.Plaid.initialize(application)
val linkConfiguration: LinkConfiguration = LinkConfiguration
              .Builder()
              .clientName(getString(R.string.app_name)) //application name
              .environment(getPlaidEnvironment()) // PlaidEnvironment.SANDBOX or PlaidEnvironment.PRODUCTION 
              .publicKey(public_key) //Dynamic public key
              .products(listOf(PlaidProduct.AUTH))
              .webhook(webhook_url)
              .token(pubToken) // if token avaialable 
              .logLevel(if (BuildConfig.DEBUG) com.plaid.link.configuration.LinkLogLevel.VERBOSE else com.plaid.link.configuration.LinkLogLevel.ASSERT)
              .build()

      com.plaid.link.Plaid.openLink(
              activity = this, //activity context
              linkConfiguration = linkConfiguration)
```

We can not reproduce it but multiple crash reports are available at the firebase crash analytics dashboard. The crash report is already provided on questions.

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo we have discovered the issue and are working on a fix, thanks for the information!

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo please try upgrading to version 2.1.1

**Comment by hitesh-banknovo** [comment]
Is it resolved in version 2.1.1?

**Comment by zsweigart** [comment]
Yes it! The issue was caused when by the Plaid class not being re-initialized when the process was killed.  Our sample didn't uncover the issue because it initialized the Plaid class in the `Application.onCreate` method.

**Comment by hitesh-banknovo** [comment]
Thank for your clarification. 

I have updated to 2.1.1 but `LinkConfiguration` class is deprecated and a new class is introduced `LinkTokenConfiguration` for that. But I could not found a way to configure parameters (public key, client name etc) in this new class. There is `extraParams` map is available but could not figure out the key string value for each parameter.

Also, the sample app is using `LinkConfiguration` in `2.1.1` version I did the same thing. Hope it will solve my firebase crash issue.

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo the `LinkConfiguration` was deprecated as we are moving to a new integration using server side configurations and one time use tokens.  There was a delay with the server-side changes but they are coming soon.  In the meantime you can continue to use the `LinkConfiguration` class with a public key.  Sorry about the confusion.

The `extraParams` map is used for handling new features in old versions if you are unable to update your SDK version.  If that is the case please reach out to your account representative and we can help set it up, otherwise we highly recommend keeping up to date with the latest version.  The `extraParams` map will not be used for the fields that have been removed between `LinkConfiguration` and `LinkTokenConfiguration`.

If the crash is resolved on your end please let us know and we'll close out this issue.

**Comment by hitesh-banknovo** [comment]
Hi, Thanks for the detailed clarification on new version changes. I will update here about the crash.

**Comment by jchio001** [comment]
Hello! We're also seeing this issue and updating to `2.1.1` (previously on `2.0.0`) did not fix the crash for us: we're still seeing users experiencing this crash on Crashlytics.

**Comment by zsweigart** [comment]
Hi @jchio001 can you provide any steps to reproduce? On our end we used the following steps which no longer reproduce the crash in 2.1.1

1. Setup the application to call Plaid.Initialize not in Application.onCreate (e.g. an Activity Start or button click)
2. Turn on Do Not Keep Activities and No Background processes in Developer options on the device
3. Open link
4. Background the App
5. Reopen the App -> Crash

**Comment by zsweigart** [comment]
Hi @jchio001 and @hitesh-banknovo, sorry for the inconvenience, it appears our fix was incorrectly missed in our 2.1.1 build. We have released 2.1.2 and will investigate how to prevent this error in the future.

**Comment by hitesh-banknovo** [comment]
Still got the crash report on version 2.1.1

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.plaid.link.internal.LinkActivity}: kotlin.UninitializedPropertyAccessException: lateinit property component has not been initialized
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Caused by kotlin.UninitializedPropertyAccessException: lateinit property component has not been initialized
       at com.plaid.link.Plaid.getComponent$link_sdk_web_release(Plaid.java:1)
       at com.plaid.link.internal.LinkActivity.onCreate(LinkActivity.java:2)
       at android.app.Activity.performCreate(Activity.java:6955)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo thanks for the response. 2.1.1 had an error so we released 2.1.2 on July 22nd.  Could you check with that?

**Comment by hitesh-banknovo** [comment]
In version 2.0.1, how can I set dynamic public key (We are fetching it from our server) and plaid environment (SANDBOX, PRODUCTION)? I could not find these parameters in `LinkTokenConfiguration`.

Also `LinkConfiguration` is deprecated but still should I need to use it with 2.0.1 version? Since it giving all these parameters and easy to configure.

**Comment by amytang0** [comment]
Hi Hitesh, `LinkTokenConfiguration` is for the new one time password tokens (https://plaid.com/docs/#create-link-token).

You would want to use the deprecated `LinkConfiguration` if you want to continue using `public_key`

**Comment by JeroenMols** [comment]
Thanks for reporting. 

Since we haven't heard back from you in a while, we are assuming this no longer is an issue for you. Please don't hesitate to reopen/file a new issue should this issue still persist on the latest SDK version.
